### ISSUE TITLE
Add logo and banner

### ISSUE THREAD

**Issue by olivernybroe** [olivernybroe/collector-intellij#1]
The plugin needs a logo and a banner! 😲 

We should consider adding that in!

IntelliJ has some requirements for the logo which we have to follow.
https://jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html

**Comment by olivernybroe** [comment]
@caneco? 🙏

**Comment by caneco** [comment]
Any ideas for the logo? Or can I go crazy? 😁

**Comment by olivernybroe** [comment]
@caneco You can go crazy! 🖍️ 

Thought that maybe something going on the pun collector, like coin collector, but I always love to see what you come up with, so go crazy 🐲
