### ISSUE TITLE
It makes my PHPSTORM code inspections to be so slow

### ISSUE THREAD

**Issue by Yi-pixel** [olivernybroe/collector-intellij#114]
This is the exception information reported by PHPSTORM.(I will attach the idea.log later)

![Snipaste_2022-03-25_15-29-15](https://user-images.githubusercontent.com/31845646/160074638-afe0b379-19ff-45e2-af76-bd18a8a13be7.png)

I find it easier to trigger these exceptions when my code is in a foreach with too many judgments. (usually PHPSTORM sends me a notification in the bottom right corner)

As soon as this happens to PHPSTORM, my PHPSTORM's code check becomes unresponsive, like freeze frame there.

![1648188266378_Snipaste_2022-03-25_14-04-18](https://user-images.githubusercontent.com/31845646/160075126-a862a6aa-633a-4913-8a6a-e9d8f6f6c5a4.png)

Like this judgment, it's in a foreach , these check hints shouldn't exist because I perfected my statement, but in fact it stays like this until I restart PHPSTORM, which is annoying.

The following idea.log is what I collected after clearing the idea.log and reopening PHPSTORM, I hope it will help you.

Please reply to me if any additions are needed.

Also, I currently have no way to provide the source code for the problem (it belongs to my organization), so I may not be able to provide a MWRE yet, but I will try to reproduce and add to it later.

[idea-copied.log](https://github.com/olivernybroe/collector-intellij/files/8348875/idea-copied.log)

**Comment by olivernybroe** [comment]
Thanks for reporting the issue!

I'll see if I can reproduce it from the stacktrace, if not I'll ask for some reproducible code 👍

**Comment by Yi-pixel** [comment]
I thought I should add more information, what I'm currently using is:

- PHP 7.1.33
- Windows 10 21H2 (19044.1586)
- Laravel 5.1.46
- PhpStorm 2021.3.3
  > Build #PS-213.7172.28, built on March 17, 2022

**Comment by olivernybroe** [comment]
In v0.4.0 this issue has been resolved. 

The Higher order type provider was giving some issues and unexpected results. So to solve this I have chosen to disable this part of the plugin.
As this part kept giving issues, it also resolved in the performance issues you experiences.
