### ISSUE TITLE
Installation misses requirement of enabled inspections

### ISSUE THREAD

**Issue by Gummibeer** [olivernybroe/collector-intellij#15]
Hey,

at first nothing worked - after checking the PR code I've seen that it's added as an inspection. It should be added to the installation part that it should be checked that the inspections are enabled as otherwise also the refactoring isn't available.

**Comment by olivernybroe** [comment]
Hmm, so the inspections were not enabled by default when you installed it?

Either way I think it's a good idea to add a configuration part in the docs, thanks! 👍

**Comment by olivernybroe** [comment]
@Gummibeer I have updated the readme to tell the user about enabling the inspections, thanks!

**Comment by Gummibeer** [comment]
Hey,

I've found the reason for the disabled inspections - there's a checkbox below the list.

![Uploading Bildschirmfoto 2020-11-09 um 12.16.18.png…]()

**Comment by olivernybroe** [comment]
@Gummibeer nice!

So it looks like IntelliJ automatically toggles this, if you have made any custom changes to your inspections.

I think we should make a pop-up notification each time your startup the IDE, telling you to enable the inspections, if they are disabled 👍

**Comment by olivernybroe** [comment]
![image](https://user-images.githubusercontent.com/5870441/98938202-d5ec2380-24e7-11eb-8143-43bad412eb25.png)
Adding the following notification, should help for people who has that setting enabled 👍
