### ISSUE TITLE
Closure to Arrow Function - Pint style matching

### ISSUE THREAD

**Issue by TWithers** [olivernybroe/collector-intellij#166]
I have been using this plugin for a while and have pretty much always (with maybe 1 or 2 exceptions) accepted the refactor provided.

One minor issue/annoyance is the Closure/Callback to Arrow Function replacement. Since the Laravel ecosystem comes bundled with Pint now, Pint has become our defacto styling standard with minimal tweaks. One of the standards that Pint sets is that there are spaces before function/method parameters:
```php
function foo ($bar) { }
$collection->map(function ($item) { });
$collection->map(fn ($item) => $item);
```

Currently, the plugin's handles the conversion from a callback to arrow function like this:
```php
$collection->map(function ($item) { return $item; });

// Becomes:

$collection->map(fn($item) => $item);
```

This immediately triggers our Pint syntax highlighter that it now needs to fix the formatting.

What would be ideal is for the plugin to detect if there was a space between "function" and the opening parenthesis, and copy that over the arrow function if it exists. This would solve the problem for those that use Pint with defaults, and those who have tweaked Pint's settings or don't care about spaces.

**Comment by olivernybroe** [comment]
Hey 👋 

We should be able to force the spacing in, but what the plugin does is actually rely on your IntelliJ coding style settings. 

Could you try and set <kbd>Editor</kbd> <kbd>></kbd> <kbd>Code Style</kbd> <kbd>></kbd> <kbd>PHP</kbd> <kbd>Spaces</kbd> <kbd>Arrow function parentheses</kbd> to  <kbd>true</kbd> and see if that fixes it for you?

**Comment by TWithers** [comment]
Perfect! I had no idea that setting existed.

**Comment by olivernybroe** [comment]
However a good suggestion would be to open an issue on phpstorm about them setting these settings automatically based on pint settings 👀 
I think that would be very valuable that phpstorm automatically takes the pint configs.
