### ISSUE TITLE
foreach statement with $key => $value doesn't refactored to collection

### ISSUE THREAD

**Issue by octoper** [olivernybroe/collector-intellij#17]
When trying to refactor the `foreach` statement with a `$key => $value` to a collection it doesn't do anything.
```php
foreach ($keys as $key => $value) {
     if (is_numeric($key)) {
         [$key, $value] = [$value, null];
     }

    $config[$key] = Arr::get($this->items, $key, $value);
}
```

The expected is to be:

```php
collect($keys)->each(function ($value, $key) {
    if (is_numeric($key)) {
         [$key, $value] = [$value, null];
     }

    $config[$key] = Arr::get($this->items, $key, $value);
});
```

Tried to solved it but I'm not very familiar with Kotlin 😅

**Comment by olivernybroe** [comment]
Did the refactoring option appear for you? 
If not, check your preferences to enable it
https://github.com/olivernybroe/collector-intellij#configuration

**Comment by octoper** [comment]
It's shows the option to refactoring but when I clicking it nothing happens

**Comment by olivernybroe** [comment]
@octoper Cool, thanks! 

I was able to reproduce it.

**Comment by olivernybroe** [comment]
[Collector-0.0.1-EAP.5.zip](https://github.com/olivernybroe/collector-intellij/files/5487847/Collector-0.0.1-EAP.5.zip)
Could you try and install this version? Should fix it 👍

**Comment by octoper** [comment]
It works now!

But I spotted another bug the uses statement add `$this` as a parameter.
![Screenshot from 2020-11-04 15-22-48](https://user-images.githubusercontent.com/6823226/98123172-ccdcd000-1eb1-11eb-8830-f2708231a94e.png)

**Comment by olivernybroe** [comment]
Ah, nice. I'll filter that one out also 👍

**Comment by olivernybroe** [comment]
Just made a new EAP release. It has the fix for `this` also. 

You can find it under GitHub releases or it should appear under marketplace in a couple of days
