### ISSUE TITLE
function() => fn() exception

### ISSUE THREAD

**Issue by zoker68** [olivernybroe/collector-intellij#183]
Hello. 
If you will solve this problem, it will good:
https://stackoverflow.com/questions/79046079/different-results-for-function-and-fn-php

In this case you plugin help with refactoring.

Tnks.

**Comment by olivernybroe** [comment]
Hey👋 Hmm seems like we might need to just disable it on `each` method calls 🤔 

Or perhaps change it to be available as a fix, but not highlight anything when it's on the `each` method.

**Comment by olivernybroe** [comment]
This has been solved as part of next release. (2-3 days)
