### ISSUE TITLE
Indentation causes invalid `flatMap` code replacement

### ISSUE THREAD

**Issue by squatto** [olivernybroe/collector-intellij#19]
I have the following code:

```php
collect($shopifyOrder->fulfillments)
    ->map(
        fn (ShopifyFulfillment $fulfillment) => $this->mapLineItems($order, $shopifyOrder, $fulfillment)
    )
    ->flatten(1);
```

It correctly suggests that I should use flatMap, but when I apply the refactoring, it ends up like this:

```php
collect($shopifyOrder->fulfillments)
    flatMapmap(
        fn (ShopifyFulfillment $fulfillment) => $this->mapLineItems($order, $shopifyOrder, $fulfillment)
    );
```

Note the `flatMapmap(` instead of `->flatMap(`

However, if I change the original code by pulling `->map(` up to the previous line:

```php
collect($shopifyOrder->fulfillments)->map(
        fn (ShopifyFulfillment $fulfillment) => $this->mapLineItems($order, $shopifyOrder, $fulfillment)
    )
    ->flatten(1);
```

It correctly refactors:

```php
collect($shopifyOrder->fulfillments)->flatMap(
        fn (ShopifyFulfillment $fulfillment) => $this->mapLineItems($order, $shopifyOrder, $fulfillment)
    );
```

I'd be happy to provide more examples or to help in any way. Thanks!

**Comment by olivernybroe** [comment]
Haha, that's an interesting bug! 

Thanks for reporting it ♥️

**Comment by olivernybroe** [comment]
I think I got this fixed now also 👍 
You can install it manually here, I'll queue up a new release soon with the fixes. So they will also be available in the marketplace in a few days.
[Collector-0.0.1-EAP.6.zip](https://github.com/olivernybroe/collector-intellij/files/5492838/Collector-0.0.1-EAP.6.zip)

**Comment by squatto** [comment]
My pleasure! I know the pain that comes with "this is broken<end>" issues 😂 

Thanks for jumping on this (and #20) so quickly 👍🏻 I'll give the updated build a try right now. I found another weird `foreach`/`use` issue that I'll send over on #20 if the new build doesn't fix it.
