### ISSUE TITLE
Multiple `use` issues when refactoring foreach to collection

### ISSUE THREAD

**Issue by squatto** [olivernybroe/collector-intellij#20]
I've come across a few situations that cause "Refactor foreach to collection" to not work correctly when it decides which variables need to be in `use`. I've provided detail on each issue below. Thanks!

---

### Issue 1: missing variable from `use`

Using the main variable `$foo` in the loop _doesn't_ lead to it being included in `use`:

```php
// original
foreach ($foo as $baz) {
    blah($foo, $baz);
}

// refactored
// missing `$foo` variable in `use`
collect($foo)->each(function ($baz) {
    blah($foo, $baz);
});
```

---

### Issue 2: duplicate variable in `use`

Adding a property accessor to the main variable `$foo` causes the main variable to be included twice in `use`:

```php
// original
foreach ($foo->bar as $baz) {
    blah($foo, $baz);
}

// refactored
// duplicate `$foo` variable in `use`
collect($foo->bar)->each(function ($baz) use ($foo, $foo) {
    blah($foo, $baz);
});
```

---

### Issue 3: unnecessary variable in `use`

If you have a property accessor on the main variable `$foo` but you _don't_ use the main variable in the loop, it is still included in `use`:

```php
// original
foreach ($foo->bar as $baz) {
    blah($baz);
}

// refactored
// unnecessary `$foo` variable in `use`
collect($foo->bar)->each(function ($baz) use ($foo) {
    blah($baz);
});
```

If you remove the property accessor from the main variable `$foo` then this issue doesn't happen:

```php
// original
foreach ($foo as $baz) {
    blah($baz);
}

// refactored
// perfect!
collect($foo)->each(function ($baz) {
    blah($baz);
});
```

**Comment by olivernybroe** [comment]
This is really awesome! 

Thanks a lot, having the before/after is really helpful as it makes it so easy for me to create a test based on it.

**Comment by olivernybroe** [comment]
I think I got them all fixed now! If you want to try it out before I make the release (will fix the other bug you reported before making the release) you can try it out by manually installing this one
[Collector-0.0.1-EAP.6.zip](https://github.com/olivernybroe/collector-intellij/files/5492655/Collector-0.0.1-EAP.6.zip)
https://github.com/olivernybroe/collector-intellij#installation
