### ISSUE TITLE
Support specifying type on collections

### ISSUE THREAD

**Issue by olivernybroe** [olivernybroe/collector-intellij#23]
It would be really awesome if we could find a way to make phpstorm understand the type which a collection returns.

This might be possible in phpstorm 2020.3 as they are adding generic supports via template syntax.

Let's analyse if we can add something like the following syntax
```
@return Collection<ComplianceForm>
```

**Comment by ekvedaras** [comment]
Can't we parse it out from this ? :)

```php
/** @return Collection|ComplianceForm[] */
```

I tend to use it since it then woks with `foreach` and just informs me what's inside :)

**Comment by olivernybroe** [comment]
@ekvedaras That should also be possible yep 👍 

The syntax I proposed and your syntax is both supported by phpstan. My proposed syntax is the generics solution, which PhpStorm should have support for now also. 

So I guess we can actually rely on PhpStorm for most of the work here, we "just" have to inform phpstorm somehow that Collections can have a type. 
This might be possible by supplying a stub of the Collection class where we use the generics syntax on it. Have to test this out of course.

**Comment by ekvedaras** [comment]
Won't it be returned by fetching the declaredType of the variable? So like you said phpstorm does all the work basically.

**Comment by olivernybroe** [comment]
Yeah, so looks like we have to use php type providers. 
It at least seems like the template syntax is still pretty unstable in phpstorm and cannot handle all the features we need for making collections work.

**Comment by olivernybroe** [comment]
So I am closing this issue, had a sorta working build locally, however phpstorm will not get native support for this, so no reason for this plugin to try and solve it also 👍
