### ISSUE TITLE
Another `use` issue when refactoring foreach to collection

### ISSUE THREAD

**Issue by squatto** [olivernybroe/collector-intellij#25]
I found another `use` issue when refactoring `foreach` to a collection. I upgraded to v0.0.1-EAP.6 so that #19 and #20 are fixed, but this issue still happens:

### When the object property IS NOT in quotes it works great:

```php
// original
foreach ($array as $value) {
    echo $value->property;
}

// refactored
// correct!
collect($array)->each(function ($value) {
    echo $value->property;
});
```

### When the object property IS in quotes it refactors incorrectly: 

```php
// original
foreach ($array as $value) {
    echo "$value->property";
}

// refactored
// no variable name in the `use` statement
collect($array)->each(function ($value) use ($) {
    echo "$value->property";
});
```

**Comment by olivernybroe** [comment]
Oh wauw, that's a wierd one :O 

And good job on the testing! I'll add some test cases for string interpolation :)

**Comment by olivernybroe** [comment]
@squatto btw. if you ever want to, you can fairly easy add the bugs you find as failing test cases and then I'll fix them :) 

You basically already wrote all the code needed for the test 😂 Else if you are okay with it, I'll just co-author you in my pr

**Comment by olivernybroe** [comment]
So apparently phpstorm sees expressions inside strings as an empty variable. I have added so we filter out empty variables now 👍

**Comment by squatto** [comment]
@olivernybroe oh sweet, I didn't even think to add failing tests to surface bugs. If I come across any more, I'll do that!

Thanks!
