### ISSUE TITLE
[foreach-to-collection] non-fixable warning given for @foreach blade directive

### ISSUE THREAD

**Issue by erikgaal** [olivernybroe/collector-intellij#28]
Hi there,

First of all, thank you for creating this plugin!

When running my inspections through my entire project, I ran into this case where it reports the `'foreach' used instead of 'Collection' inspection in a Blade template. Blade uses [directives for loops](https://laravel.com/docs/8.x/blade#loops), which use traditional `foreach (...) { }` syntax.

```blade
@foreach ($items as $item)
  <li>{{ $item }}</li>
@endforeach
```

The warning caused by the plugin cannot be refactored automatically because of the different syntax, and I don't think the Collection alternative should be preferred in contrast to Blade directives.

Is it possible to detect the difference as a plugin, and can we ignore cases like the one above?

Kind regards,
Erik Gaal

**Comment by olivernybroe** [comment]
Ah, that's interesting. 
Thought I had to do something special for making it apply to blade files also.

So obviously we should not run this inspection on blade files or better yet, if we can exclude it from blade directive, I think that's better. 

So before i have a fix for it, you might be able to disable the inspection on blade files by using scopes?

**Comment by olivernybroe** [comment]
A quick look into this, I think we will just disable the inspection, as long as we are running in blade files. 

Making the check to see if it's a blade directive, will do so this plugin requires the blade plugin, which not all users necessarily has installed.

**Comment by olivernybroe** [comment]
Hi @erikgaal,

Think I got a fix for this now, it will be rolled out later today. (will still take up to 2 days before available in marketplace
[Collector-0.0.1-EAP.8.zip](https://github.com/olivernybroe/collector-intellij/files/5510456/Collector-0.0.1-EAP.8.zip)

**Comment by erikgaal** [comment]
Awesome! Thanks for your hard work. 👍
