### ISSUE TITLE
Wrong recursive call on collection detected

### ISSUE THREAD

**Issue by def-studio** [olivernybroe/collector-intellij#39]
first: thumbs up for your awesome work, it's a great efficiency increase in my workflow :+1: 

issue: if I have a function that returns mixed content a **recursive call on collection** warning is shown

![image](https://user-images.githubusercontent.com/8792274/102477770-14cc4680-405d-11eb-9c54-d06e872a0c43.png)

`->get_config()` returns `\Illuminate\Config\Repository|\Illuminate\Contracts\Foundation\Application|mixed`

![image](https://user-images.githubusercontent.com/8792274/102477906-42b18b00-405d-11eb-81ae-5b8ee3b3f744.png)

notes: collector v. 0.2.0.EAP.1

**Comment by olivernybroe** [comment]
Ah, thank you for reporting this. 

Apparently IntelliJ tells us that `mixed` is of type `Collection`. I'll try and sort it out 👍

**Comment by olivernybroe** [comment]
Hmm, this is wierd. So I remember I did something related to this already.

We have a test for checking if it ignores mixed type and it does 🤔

Trying to figure out how to reproduce this in a tests 👍

**Comment by def-studio** [comment]
I'll try to reproduce it in a clean project too, it should be helpful to you, I think

**Comment by def-studio** [comment]
it seems that the problem is not related to mixed type (it does not trigger the inspection):

![image](https://user-images.githubusercontent.com/8792274/102684328-ca230980-41d7-11eb-90a8-753a688ebbce.png)

probably, in union types, it does not take into account that the variable "could" not be a collection:

![image](https://user-images.githubusercontent.com/8792274/102684358-03f41000-41d8-11eb-85df-89ccffb4f3dc.png)

**Comment by olivernybroe** [comment]
@def-studio ah of course!

With all the other collection inspections we are fine with the collection variable might be something else. However when checking for recursive calls we have to make a more strict check on the type. Great catch, I'll try and make a test case for this.


It's fine, for me what I need is a small php snippet not depending on anything else, like the one you just gave me. That will make it possible for me to write a test.

**Comment by def-studio** [comment]
sounds great! 

again, awesome work!

**Comment by olivernybroe** [comment]
@def-studio Could you check out of this version fixes it for you?

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>

[Collector-0.2.0.EAP.2.zip](https://github.com/olivernybroe/collector-intellij/files/5720684/Collector-0.2.0.EAP.2.zip)

**Comment by def-studio** [comment]
> @def-studio Could you check out of this version fixes it for you?
> 
> Install it manually using
> Preferences > Plugins > ⚙️ > Install plugin from disk...
> 
> [Collector-0.2.0.EAP.2.zip](https://github.com/olivernybroe/collector-intellij/files/5720684/Collector-0.2.0.EAP.2.zip)

Ok! I'll do in a couple of hours!

**Comment by def-studio** [comment]
"human testing" completed: 1/1

seems ok!

first call is not detected as recursive, second one is (rightfully) detected

![image](https://user-images.githubusercontent.com/8792274/102710409-59045480-42b2-11eb-8348-04ed9fe1642c.png)

great job!

**Comment by olivernybroe** [comment]
Thanks! I'll release the next EAP then 👍 

Added you as co-author because you did all the investigation work for me. 
You do not have to do anything btw. You already have the next EAP installed and when a new version is out, it will still prompt you as normal to install the update, even though you just did a manual install.
