### ISSUE TITLE
Error adding Custom Plugin Repository

### ISSUE THREAD

**Issue by skylerkatz** [olivernybroe/collector-intellij#8]
Hello,

I am using PHPStorm 2020.3 EAP and when I try to add the custom repository `https://plugins.jetbrains.com/plugins/eap/15246` it says that there is nothing found.

![Screen Shot 2020-10-23 at 10 49 54 AM](https://user-images.githubusercontent.com/7297992/97025307-bf683300-150c-11eb-9a87-770ea2022718.png)

Any thoughts on what the issue might be or should I just go ahead and download it manually for now?

Thanks,
Skyler

**Comment by olivernybroe** [comment]
Oh Yeah, sorry. Will update readme. 

The plugin has not been validated yet by jetbrains. They won't validate it before we get an icon 😂

So for now you have to do the manual install.

Btw. Thanks for wanting to try it out!

**Comment by olivernybroe** [comment]
@skylerkatz Hi! So we got an icon and approval for the plugin.

It is now possible to install it via EAP version 👍
